-- AlterTable
ALTER TABLE "Profil" ALTER COLUMN "title" DROP NOT NULL,
ALTER COLUMN "title" DROP DEFAULT,
ALTER COLUMN "subTitle" DROP NOT NULL,
ALTER COLUMN "subTitle" DROP DEFAULT;

-- AlterTable
ALTER TABLE "ProfilItem" ALTER COLUMN "label" DROP NOT NULL,
ALTER COLUMN "label" DROP DEFAULT,
ALTER COLUMN "uri" DROP NOT NULL,
ALTER COLUMN "uri" DROP DEFAULT;
